name: ayna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  go_router: ^13.2.2
  get_it: ^7.6.4
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.7
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  flutter_screenutil: ^5.9.0
  email_validator: ^2.1.17
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.3.0
  flutter_gen: ^5.4.0
  internet_connection_checker_plus: ^2.2.0
  timeago: ^3.6.1
  gif: ^2.2.0
  path: ^1.9.0
  shimmer: ^3.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  web_socket_channel: ^3.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
          style: italic
